package com.mainstation.app.ui.screens.booking

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.mainstation.app.data.model.Booking
import com.mainstation.app.data.repository.BookingRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.launch
import javax.inject.Inject
import com.mainstation.app.data.repository.AuthRepository
import java.util.Date

@HiltViewModel
class BookingViewModel @Inject constructor(
    private val repository: BookingRepository,
    private val authRepository: AuthRepository
) : ViewModel() {

    private val _bookingResult = MutableSharedFlow<Result<Unit>>()
    val bookingResult: SharedFlow<Result<Unit>> = _bookingResult

    fun submitBooking(
        roomId: String?,
        consoleId: String?,
        duration: Int,
        hourlyRate: Double,
        location: String = "Malioboro"
    ) {
        viewModelScope.launch {
            val user = authRepository.getCurrentUser()
            if (user == null) {
                _bookingResult.emit(Result.failure(Exception("User not not logged in")))
                return@launch
            }

            val startTime = Date()
            val endTime = Date(System.currentTimeMillis() + (duration * 3600000L))
            val total = duration * hourlyRate

            val booking = Booking(
                id = "", // Will be generated by Repository
                userId = user.id,
                consoleId = consoleId,
                roomId = roomId,
                startTime = startTime,
                endTime = endTime,
                duration = duration,
                total = total,
                status = "PENDING",
                location = location
            )

            val result = repository.createBooking(booking)
            _bookingResult.emit(result)
        }
    }
}
